# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "pixivcat-cloudflare-workers"
main = "index.js"
compatibility_date = "2024-03-20"
account_id = ""
compatibility_flags = []
workers_dev = true

[vars]
PIXIV_API_ENDPOINT = "app-api.pixiv.net"
PIXIV_OAUTH_ENDPOINT = "oauth.secure.pixiv.net"

[placement]
mode = "off"