name = "pixivcat-cloudflare-workers"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-01-10"

[vars]
PIXIV_API_ENDPOINT = "app-api.pixiv.net"
PIXIV_OAUTH_ENDPOINT = "oauth.secure.pixiv.net"
